on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16 LTS
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: ${{ secrets.ftp_server_dir }}
          dangerous-clean-slate: false
          dry-run: true
          log-level: verbose
